// Mock products for when Supabase is not connected
export const MOCK_PRODUCTS = [
  {
    id: "prod-001",
    name: "Silk Balconette Bra",
    slug: "silk-balconette-bra",
    description:
      "Crafted from pure silk charmeuse with delicate French lace trim. Features adjustable straps and underwire support for the perfect lift.",
    longDescription:
      "This exquisite balconette bra features pure silk charmeuse paired with hand-finished French lace trim. The underwire construction provides excellent support while the adjustable straps ensure a perfect fit.",
    price: 89,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1599836641623-a596a2c44abc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["32B", "34B", "34C", "36B", "36C"],
    colors: ["Blush", "Black", "Ivory"],
    inStock: true,
    stockCount: 25,
    badge: "NEW",
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "prod-002",
    name: "Vintage Lace Set",
    slug: "vintage-lace-set",
    description:
      "A timeless two-piece featuring hand-finished Chantilly lace. The bralette offers light support while the high-waisted brief creates a flattering silhouette.",
    longDescription:
      "This romantic lingerie set showcases the finest hand-finished Chantilly lace. The wireless bralette provides gentle support while the high-waisted brief offers a vintage-inspired silhouette.",
    price: 148,
    originalPrice: 178,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Black", "Rose"],
    inStock: true,
    stockCount: 20,
    badge: "SALE",
    rating: 4.9,
    reviewCount: 31,
    featured: true,
    createdAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "prod-003",
    name: "Satin Sleep Chemise",
    slug: "satin-sleep-chemise",
    description:
      "Luxurious bias-cut chemise in pure silk satin. Adjustable shoulder straps and a fluid drape for ultimate comfort.",
    longDescription:
      "Cut on the bias for a beautiful drape, this chemise is crafted from the finest silk satin. Features delicate adjustable straps and a flattering V-neckline.",
    price: 124,
    originalPrice: undefined,
    category: "sleepwear",
    image:
      "https://images.unsplash.com/photo-1770294758971-44fa1eae61a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1770294758971-44fa1eae61a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1742794555175-0e55d742d809?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Noir", "Blush"],
    inStock: true,
    stockCount: 27,
    badge: undefined,
    rating: 4.7,
    reviewCount: 18,
    featured: true,
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "prod-004",
    name: "High-Waist Brief",
    slug: "high-waist-brief",
    description:
      "Elegant high-waisted brief in Italian silk blend. Features a comfortable elastic waistband and full coverage.",
    longDescription:
      "Combining comfort with elegance, this high-waisted brief is made from an Italian silk blend. The wide waistband sits comfortably at the natural waist.",
    price: 45,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rose", "Black", "Nude", "Ivory"],
    inStock: true,
    stockCount: 63,
    badge: undefined,
    rating: 4.6,
    reviewCount: 42,
    featured: false,
    createdAt: "2026-02-10T00:00:00Z",
  },
  {
    id: "prod-005",
    name: "French Lace Bralette",
    slug: "french-lace-bralette",
    description:
      "Soft triangle bralette in delicate Calais lace. Wire-free design with adjustable back closure for customized fit.",
    longDescription:
      "This romantic triangle bralette features delicate Calais lace in a wire-free design. The adjustable hook-and-eye closure ensures a perfect fit.",
    price: 68,
    originalPrice: 82,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1620228681518-5f0e3e29940d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1620228681518-5f0e3e29940d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1620228800601-4723775ab061?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Ivory", "Burgundy"],
    inStock: true,
    stockCount: 26,
    badge: "SALE",
    rating: 4.8,
    reviewCount: 35,
    featured: true,
    createdAt: "2026-02-15T00:00:00Z",
  },
  {
    id: "prod-006",
    name: "Silk Robe",
    slug: "silk-robe",
    description:
      "Floor-length robe in lustrous silk charmeuse. Self-tie belt and deep pockets for the ultimate loungewear experience.",
    longDescription:
      "This luxurious floor-length robe is crafted from lustrous silk charmeuse. Features a self-tie belt, deep side pockets, and wide sleeves for ultimate elegance.",
    price: 198,
    originalPrice: undefined,
    category: "sleepwear",
    image:
      "https://images.unsplash.com/photo-1750064139819-da3bf362e7b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1750064139819-da3bf362e7b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1770294759006-356f25f4f156?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S/M", "L/XL"],
    colors: ["Nude", "Champagne", "Navy"],
    inStock: true,
    stockCount: 8,
    badge: undefined,
    rating: 5.0,
    reviewCount: 12,
    featured: true,
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "prod-007",
    name: "Mesh Thong",
    slug: "mesh-thong",
    description:
      "Barely-there thong in Italian mesh with silk trim. Invisible under clothing with a flattering low-rise waist.",
    longDescription:
      "This minimal thong features ultra-fine Italian mesh with delicate silk trim. The low-rise waist and minimal coverage make it invisible under clothing.",
    price: 32,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Nude", "Black"],
    inStock: true,
    stockCount: 92,
    badge: undefined,
    rating: 4.5,
    reviewCount: 67,
    featured: false,
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "prod-008",
    name: "Embroidered Plunge Bra",
    slug: "embroidered-plunge-bra",
    description:
      "Deep plunge bra with hand-embroidered floral motif. Underwire and lightly padded cups for support and shaping.",
    longDescription:
      "This stunning plunge bra features a hand-embroidered floral motif across sheer mesh. Underwire construction and light padding provide excellent support and shaping.",
    price: 95,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1610241519159-8a62634bac9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1610241519159-8a62634bac9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["32C", "34C", "34D", "36C", "36D"],
    colors: ["Burgundy", "Black", "Blush"],
    inStock: true,
    stockCount: 20,
    badge: undefined,
    rating: 4.7,
    reviewCount: 28,
    featured: false,
    createdAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "prod-009",
    name: "Satin Pajama Set",
    slug: "satin-pajama-set",
    description:
      "Classic button-up pajama set in silk satin. Contrast piping detail and relaxed fit for ultimate comfort.",
    longDescription:
      "This elegant pajama set features a classic button-up top and relaxed pants in luxurious silk satin. Contrast piping adds a refined detail.",
    price: 165,
    originalPrice: 195,
    category: "sleepwear",
    image:
      "https://images.unsplash.com/photo-1770294760762-1cd821ecc567?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1770294760762-1cd821ecc567?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1770294758967-6ed2b93ce42c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Navy", "Champagne", "Rose"],
    inStock: true,
    stockCount: 22,
    badge: "SALE",
    rating: 4.9,
    reviewCount: 19,
    featured: true,
    createdAt: "2026-03-20T00:00:00Z",
  },
  {
    id: "prod-010",
    name: "Lace Triangle Set",
    slug: "lace-triangle-set",
    description:
      "Delicate triangle bralette and matching bikini brief in stretch lace. Soft, wire-free design with adjustable straps.",
    longDescription:
      "This beautiful set features a wire-free triangle bralette and matching bikini brief in soft stretch lace. The adjustable straps ensure a perfect fit.",
    price: 112,
    originalPrice: undefined,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Dusty Pink", "Black", "Ivory"],
    inStock: true,
    stockCount: 32,
    badge: undefined,
    rating: 4.6,
    reviewCount: 21,
    featured: false,
    createdAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "prod-011",
    name: "Demi Cup Lace Bra",
    slug: "demi-cup-lace-bra",
    description:
      "Elegant demi cup design in floral lace with scalloped edges. Perfect for everyday wear with a touch of luxury.",
    longDescription:
      "This demi cup bra features intricate floral lace with beautiful scalloped edges. The underwire construction provides support while the demi cup offers a flattering neckline.",
    price: 78,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1620228800601-4723775ab061?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1620228800601-4723775ab061?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1620228681518-5f0e3e29940d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["32B", "34B", "34C", "36C", "36D"],
    colors: ["Sapphire", "Black", "Nude"],
    inStock: true,
    stockCount: 18,
    badge: undefined,
    rating: 4.7,
    reviewCount: 29,
    featured: false,
    createdAt: "2026-03-25T00:00:00Z",
  },
  {
    id: "prod-012",
    name: "Wireless Comfort Bra",
    slug: "wireless-comfort-bra",
    description:
      "Ultra-soft wireless bra in modal blend. All-day comfort with seamless construction and removable padding.",
    longDescription:
      "Designed for ultimate comfort, this wireless bra features a soft modal blend fabric with seamless construction. Removable padding allows for customizable coverage.",
    price: 52,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1599836641623-a596a2c44abc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1599836641623-a596a2c44abc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Nude", "Black", "White"],
    inStock: true,
    stockCount: 45,
    badge: undefined,
    rating: 4.9,
    reviewCount: 58,
    featured: true,
    createdAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "prod-013",
    name: "Longline Bralette",
    slug: "longline-bralette",
    description:
      "Extended longline bralette with wide band for extra support. Beautiful eyelash lace detail throughout.",
    longDescription:
      "This longline bralette extends to the ribcage for additional support and coverage. Features delicate eyelash lace and a comfortable wide elastic band.",
    price: 72,
    originalPrice: 86,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1610241519159-8a62634bac9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1610241519159-8a62634bac9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black", "Burgundy", "Ivory"],
    inStock: true,
    stockCount: 22,
    badge: "SALE",
    rating: 4.6,
    reviewCount: 33,
    featured: false,
    createdAt: "2026-03-05T00:00:00Z",
  },
  {
    id: "prod-014",
    name: "Push-Up Plunge Bra",
    slug: "push-up-plunge-bra",
    description:
      "Maximum lift and cleavage with graduated padding. Deep plunge for low necklines.",
    longDescription:
      "This push-up bra features graduated padding for natural-looking lift and a deep plunge neckline perfect for low-cut tops and dresses.",
    price: 82,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1620228681518-5f0e3e29940d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1620228681518-5f0e3e29940d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["32A", "32B", "34A", "34B", "34C"],
    colors: ["Nude", "Black"],
    inStock: true,
    stockCount: 28,
    badge: undefined,
    rating: 4.5,
    reviewCount: 41,
    featured: false,
    createdAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "prod-015",
    name: "Racerback Sports Bra",
    slug: "racerback-sports-bra",
    description:
      "High-impact support with moisture-wicking fabric. Sleek racerback design with adjustable straps.",
    longDescription:
      "Engineered for high-impact activities, this sports bra features moisture-wicking fabric and a supportive racerback design with adjustable straps for a custom fit.",
    price: 58,
    originalPrice: undefined,
    category: "bras",
    image:
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1599839770015-53df36f312a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Navy", "Rose"],
    inStock: true,
    stockCount: 35,
    badge: undefined,
    rating: 4.8,
    reviewCount: 52,
    featured: false,
    createdAt: "2026-03-12T00:00:00Z",
  },
  {
    id: "prod-016",
    name: "Lace Bikini Brief",
    slug: "lace-bikini-brief",
    description:
      "Classic bikini cut with delicate lace trim. Comfortable cotton gusset and seamless edges.",
    longDescription:
      "This bikini brief features a classic mid-rise cut with beautiful lace trim along the waistband and leg openings. Cotton gusset provides all-day comfort.",
    price: 38,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Nude", "White", "Rose"],
    inStock: true,
    stockCount: 68,
    badge: undefined,
    rating: 4.7,
    reviewCount: 73,
    featured: false,
    createdAt: "2026-03-08T00:00:00Z",
  },
  {
    id: "prod-017",
    name: "Seamless Hipster",
    slug: "seamless-hipster",
    description:
      "No-show hipster in ultra-soft microfiber. Laser-cut edges for invisible wear under clothing.",
    longDescription:
      "These seamless hipsters feature laser-cut edges that lay completely flat for invisible wear. Ultra-soft microfiber fabric provides breathable comfort.",
    price: 28,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Nude", "Black"],
    inStock: true,
    stockCount: 92,
    badge: undefined,
    rating: 4.9,
    reviewCount: 88,
    featured: true,
    createdAt: "2026-02-25T00:00:00Z",
  },
  {
    id: "prod-018",
    name: "Brazilian Cut Brief",
    slug: "brazilian-cut-brief",
    description:
      "Cheeky Brazilian cut with minimal coverage. Delicate lace waistband and satin bow detail.",
    longDescription:
      "This Brazilian brief offers moderate coverage with a flattering cheeky cut. Features a delicate lace waistband and charming satin bow detail.",
    price: 35,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pink", "Black", "Ivory"],
    inStock: true,
    stockCount: 54,
    badge: undefined,
    rating: 4.6,
    reviewCount: 62,
    featured: false,
    createdAt: "2026-03-18T00:00:00Z",
  },
  {
    id: "prod-019",
    name: "Control Brief",
    slug: "control-brief",
    description:
      "Medium control shaping brief with power mesh panels. Smooths and shapes while remaining comfortable.",
    longDescription:
      "These control briefs feature strategically placed power mesh panels that provide medium control and smoothing. High-waisted design offers tummy control.",
    price: 42,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1547714062-4daa321e1d6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Nude", "Black"],
    inStock: true,
    stockCount: 38,
    badge: undefined,
    rating: 4.8,
    reviewCount: 45,
    featured: false,
    createdAt: "2026-03-22T00:00:00Z",
  },
  {
    id: "prod-020",
    name: "G-String Thong",
    slug: "g-string-thong",
    description:
      "Minimal coverage G-string with string sides. Perfect for eliminating visible panty lines.",
    longDescription:
      "This minimal G-string features ultra-thin string sides for complete invisibility under clothing. Soft microfiber front panel ensures comfort.",
    price: 26,
    originalPrice: undefined,
    category: "briefs",
    image:
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1766927462981-78f493700a54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Nude", "Black", "White"],
    inStock: true,
    stockCount: 76,
    badge: undefined,
    rating: 4.4,
    reviewCount: 51,
    featured: false,
    createdAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "prod-021",
    name: "Floral Embroidered Set",
    slug: "floral-embroidered-set",
    description:
      "Romantic floral embroidery on sheer mesh. Balconette bra with matching high-waisted brief.",
    longDescription:
      "This stunning set features intricate floral embroidery on delicate sheer mesh. The balconette bra offers beautiful lift while the high-waisted brief creates a vintage silhouette.",
    price: 156,
    originalPrice: undefined,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black", "Burgundy"],
    inStock: true,
    stockCount: 15,
    badge: "NEW",
    rating: 4.9,
    reviewCount: 27,
    featured: true,
    createdAt: "2026-04-05T00:00:00Z",
  },
  {
    id: "prod-022",
    name: "Strappy Harness Set",
    slug: "strappy-harness-set",
    description:
      "Edgy strappy harness bralette with matching garter brief. Adjustable elastic straps for custom fit.",
    longDescription:
      "This bold set features a strappy harness bralette design with multiple adjustable elastic straps. The matching garter brief includes removable garter clips.",
    price: 134,
    originalPrice: undefined,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    inStock: true,
    stockCount: 12,
    badge: undefined,
    rating: 4.7,
    reviewCount: 19,
    featured: false,
    createdAt: "2026-03-28T00:00:00Z",
  },
  {
    id: "prod-023",
    name: "Silk & Lace Teddy",
    slug: "silk-lace-teddy",
    description:
      "One-piece teddy combining silk satin and French lace. Adjustable straps and snap closure.",
    longDescription:
      "This elegant teddy features a silk satin body with French lace details. Adjustable shoulder straps and convenient snap gusset closure.",
    price: 128,
    originalPrice: 158,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1770294758971-44fa1eae61a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1770294758971-44fa1eae61a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Champagne", "Blush"],
    inStock: true,
    stockCount: 18,
    badge: "SALE",
    rating: 4.8,
    reviewCount: 36,
    featured: false,
    createdAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "prod-024",
    name: "Sheer Mesh Set",
    slug: "sheer-mesh-set",
    description:
      "Ultra-sheer Italian mesh with strategic lace appliqués. Soft cup bralette and matching brief.",
    longDescription:
      "This daring set features ultra-sheer Italian mesh with strategically placed lace appliqués. The soft cup bralette and brief offer minimal coverage with maximum impact.",
    price: 142,
    originalPrice: undefined,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1598719830738-32b91fa649be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black", "Nude"],
    inStock: true,
    stockCount: 14,
    badge: undefined,
    rating: 4.6,
    reviewCount: 22,
    featured: false,
    createdAt: "2026-04-02T00:00:00Z",
  },
  {
    id: "prod-025",
    name: "Velvet Bralette Set",
    slug: "velvet-bralette-set",
    description:
      "Luxurious stretch velvet bralette with satin trim. Includes matching velvet brief with lace detail.",
    longDescription:
      "This opulent set features rich stretch velvet with contrasting satin trim. The wireless bralette and matching brief combine comfort with elegance.",
    price: 118,
    originalPrice: undefined,
    category: "sets",
    image:
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    images: [
      "https://images.unsplash.com/photo-1762195020829-835d05d3ee80?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Burgundy", "Emerald", "Navy"],
    inStock: true,
    stockCount: 24,
    badge: undefined,
    rating: 4.9,
    reviewCount: 41,
    featured: true,
    createdAt: "2026-03-30T00:00:00Z",
  },
];
